service: error-parser

provider:
  name: aws
  runtime: python3.8

functions:
  numpy:
    handler: parser.lambda_handler

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
