[tool.poetry]
name = "discord_app"
version = "1.0"
description = ""
authors = ["lesteenman <lesteenman@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.16.63"
discord-interactions = "^0.1.2"
"discord.py" = "^1.6.0"
pynamodb = "^5.0.2"
loguru = "^0.5.3"
deprecation = "^2.1.0"
moto = "^3.1.4"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest = "^7.1.1"
pytest-mock = "^3.5.1"
pytest-asyncio = "^0.18.3"
localstack = "^0.14.2"
pytest-env = "^0.6.2"
docker = "^5.0.3"
opnieuw = "^1.1.0"
pytest-cov = "^3.0.0"
coverage = {extras = ["toml"], version = "^5.5"}
moto = "^3.1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [".*", "*/site-packages/*"]
