[tool.poetry]
name = "discord_app"
version = "0.1.0"
description = ""
authors = ["lesteenman <lesteenman@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.16.63"
discord-interactions = "^0.1.2"
"discord.py" = "^1.6.0"
pynamodb = "^5.0.2"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
pytest = "^6.2.2"
pytest-mock = "^3.5.1"
pytest-asyncio = "^0.14.0"
localstack = "^0.12.5"
pytest-env = "^0.6.2"
moto = "^1.3.16"
docker = "^4.4.1"
opnieuw = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
