service: discord-app
frameworkVersion: ^2.21.1

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  numpy:
    handler: eternal_guesses.handler.handle_lambda

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
    slim: true
