service: discord-app
frameworkVersion: ^2.21.1

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  numpy:
    handler: eternal_guesses.api.handler.handle_lambda

plugins:
  - serverless-python-requirements

package:
  exclude:
    - tests/**
    - .venv/**

custom:
  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: true
    slim: true
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: .serverless/cache
