name: main

on:
  push:
    branches: [ main ]

  # TODO: REMOVE THIS AGAIN
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install poetry
        uses: snok/install-poetry@v1.0.0
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Load cached venv for discord-app
        id: cached-discord-app-poetry
        uses: actions/cache@v2
        with:
          path: discord_app/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('discord_app/poetry.lock') }}

      - name: Poetry install for discord_app/
        run: cd discord_app && poetry install
        if: steps.cached-discord-app-poetry.outputs.cache-hit != 'true'

      - name: Load cached venv for infra
        id: cached-infra-poetry
        uses: actions/cache@v2
        with:
          path: infra/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('infra/poetry.lock') }}

      - name: Poetry install for infra/
        run: cd infra && poetry install
        if: steps.cached-infra-poetry.outputs.cache-hit != 'true'

      - name: Load cached node modules
        id: cached-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Npm install
        run: npm install
        if: steps.cached-node-modules.outputs.cache-hit != 'true'

      - name: Flake8
        run: cd discord_app && poetry run flake8 --config ../.flake8 ./tests ./eternal_guesses ../error_parser_function ../infra

      - name: Pytest
        run: cd discord_app && poetry run pytest --cov=eternal_guesses --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: discord_app/coverage.xml
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

      - name: Package discord-app
        run: cd discord_app/ && npx serverless package && cd ../

      - name: Create artifact for the discord-app bot
        uses: actions/upload-artifact@v2
        with:
          name: discord-app-package
          path: discord_app/.serverless/discord-app.zip

      - name: Package error-parser
        run: cd error_parser_function/ && npx serverless package && cd ../

      - name: Create artifact for the error-parser
        uses: actions/upload-artifact@v2
        with:
          name: error-parser-package
          path: error_parser_function/.serverless/error-parser.zip

      - name: Create artifact for the infra module
        uses: actions/upload-artifact@v2
        with:
          name: infra
          path: infra/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore the artifact for the discord-app
        uses: actions/download-artifact@v2
        with:
          name: discord-app-package

      - name: Restore the artifact for the error-parser
        uses: actions/download-artifact@v2
        with:
          name: error-parser-package

      - name: Restore the artifact for the error-parser
        uses: actions/download-artifact@v2
        with:
          name: error-parser-package

      - name: Build Changelog
        id: changes
        run: echo "::set-output name=changeLog::$(git show --format=%B | tail +3)"

      - name: Get the date of the release
        id: release_date
        run: echo "::set-output name=date::$(date +"%Y-%m-%d")"

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.release_name.outputs.date }} ${{ GITHUB_SHA::7 }}
          release_name: ${{ steps.release_name.outputs.date }} ${{ GITHUB_SHA::7 }}
          body: ${{steps.changes.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
