name: pull-requests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Load cached venv for discord-app
        id: cached-discord-app-poetry
        uses: actions/cache@v3
        with:
          path: |
            discord_app/.venv
            discord_app/.serverless/cache
          key: venv-${{ runner.os }}-${{ hashFiles('discord_app/poetry.lock') }}

      - name: Poetry install for discord_app/
        run: cd discord_app && poetry install
        if: steps.cached-discord-app-poetry.outputs.cache-hit != 'true'

      - name: Load cached venv for infra
        id: cached-infra-poetry
        uses: actions/cache@v3
        with:
          path: infra/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('infra/poetry.lock') }}

      - name: Poetry install for infra/
        run: cd infra && poetry install
        if: steps.cached-infra-poetry.outputs.cache-hit != 'true'

      - name: Load cached node modules
        id: cached-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Npm install
        run: npm install
        if: steps.cached-node-modules.outputs.cache-hit != 'true'

      - name: Flake8
        run: cd discord_app && poetry run flake8 --config ../.flake8 ./tests ./eternal_guesses ../error_parser_function ../infra

      - name: Pytest
        run: cd discord_app && poetry run coverage run -m pytest && poetry run coverage xml

      - name: Package discord-app
        run: cd discord_app/ && npx serverless package && cd ../

      - name: Package error-parser
        run: cd error_parser_function/ && npx serverless package && cd ../

      - name: Synthesize CDK
        run: cd infra && poetry run npx cdk synth --output build/cdk.out
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_TARGET_ACCOUNT: ${{ secrets.AWS_TARGET_ACCOUNT }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
